---
# handlers file for roles_Fedora
- name: Restarted Launching  NGINX Container
  docker_container: 
    name: nginx
    image: andreysagurov/nginx
    state: started 
    restart: yes  
    exposed_ports:
      - "80"
    ports: 
      - "9999:80"
    volumes:
      - "{{ nginx_file }}/index.html:/usr/share/nginx/html/index.html"   
