# This is a basic workflow to help you get started with Actions

name: My_githubeActions
on:
  
  push:
    branches:   
       - main
jobs:
  my_testing:   
    runs-on: self-hosted 
      
    steps:
    - name: Run a one-line script
      run: echo Hello, world from testing new!
          
    - name: list folder 
      run : ls -la

    - name : Git clone my repo
      uses: actions/checkout@v2

    - name: list folder 
      run : ls -la
    
    - name: Run ansible-nginx script
      run: sudo ansible-playbook  playbook_nginx
      #run:  playbook_nginx
     #run: sudo ./playbookscript.sh

  my_deploy:
    runs-on:  ubuntu-latest
    needs: [ my_testing ]
    
    steps: 
    - name: Run a one-line script
      run: echo Hello, worlds from Deploy in Deploy ! 
      
