# This is a basic workflow to help you get started with Actions

name: My_githubeActions
env:  
  APPLICATION_NAME       : "Mynginx"
  PACKAGE_NAME    :  "nginx-deploy-ver-${{ github.sha }}"

   

on:
  
  push:
    branches:   
       - main
jobs:
  my_testing:
  
    runs-on: ubuntu-latest

   
    steps:
    - name: Run a one-line script
      run: echo Hello, world from testing new!
    - name: Execute few comands
      run: |
        echo "Hello message1"
        echo "Hello message2"
        echo "Applicationname: ${{ env.APPLICATION_NAME }}"
  my_deploy:
    runs-on:  ubuntu-latest
    needs: [ my_testing ]
    
    steps: 
    - name: Run a one-line script
      run: echo Hello, world from Deploy in Deploy! 

    - name: Printing Deplpoyment package
      run : echo "Deploy package name ${{ env.PACKAGE_NAME }}"

