# This is a basic workflow to help you get started with Actions

name: My_githubeActions
env:  
  APPLICATION_NAME       : "Mynginx"
  PACKAGE_NAME    :  "nginx-deploy-ver-${{ github.sha }}"

on:
  
  push:
    branches:   
       - main
jobs:
  my_testing:   
    runs-on: self-hosted 
    # ubuntu-latest 
     # - self-hosted
      #- label-1

   
    steps:
    - name: Run a one-line script
      run: echo Hello, world from testing new!
    - name: Execute few comands
      run: |
        echo "Hello message1"
        echo "Hello messages2"
       # echo "Applicationname: ${{ env.APPLICATION_NAME }}"
    - name: list folder 
      run : ls -la

    - name : Git clone my repo
      uses: actions/checkout@v1

    - name: list folder 
      run : ls -la
   
  #  - name: create dir
  #    run: cd /home/andy/actions-runner/_work/DOCKER_NGINX_proxy_NGINX_servers_ansible/DOCKER_NGINX_proxy_NGINX_servers_ansible
   
    - name: Run ansible-nginx script
      run: ./ansible_script.sh

  my_deploy:
    runs-on:  ubuntu-latest
    needs: [ my_testing ]
    env:
      VAR1: "This is Job level Variable1"
      VAR2: "This is Job levels Variable2"
      
    steps: 
    - name: Run a one-line script
      run: echo Hello, worlds from Deploy in Deploy! 

    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Supper local Environment varible"
    
    - name: Printing Deplpoyment packages
      run : echo "Deploy package name ${{ env.PACKAGE_NAME }}"

    - name: Lets test some packages if the are here 1
      run: aws --version
    
    - name: Lets tests some packages if the are here 2
      run: zip# This is a basic workflow to help you get started with Actions

